import Head from 'next/head';
import styles from '../styles/Home.module.css'
import {BiUserPlus} from 'react-icons/bi';
import Table from '../components/table';
import Form from '../components/form';
import { useState } from 'react';
import { UseSelector,useDispatch, useSelector } from 'react-redux';
import { toggleChangeAction,deleteAction } from '@/redux/reducer';
import { deleteVendor,getVendors } from '@/components/lib/helper';
import { useQueryClient } from 'react-query';


export default function Home() {

const visible=useSelector((state)=>state.app.client.toggleForm) // here first form will disspear when we ciick the add user button it will apear
const deleteId=useSelector((state)=>state.app.client.deleteId)

const querclient=useQueryClient()

const dispatch=useDispatch()
  const handler=()=>{
     dispatch(toggleChangeAction())                  // setvisible(visible?false:true)IT IS A FUNCTION makes visble as true if again click on that button form will disappear

  }
  const deletehandler= async(id)=>{
    if(id){
    await deleteVendor(id)
    await querclient.prefetchQuery('users',getVendors)
    await dispatch(deleteAction(null))
    }

  }
  return (
    <section className='container'>
      <Head>
        <title>vendor_app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main className="py-5">
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Vendor_Management</h1>

        <div className='container mx-auto flex justify-between py-50 border-b'>
          <div className='left flex gap-3'>
            <button onClick={handler} className='flex bg-indigo-500 text-white px-4 py-2 broder rounded-md hover:bg-gray-500 hover:border-indigo-500 hover:text-gray-800'>
              Add Vendor<span className='px-1'><BiUserPlus size={23}></BiUserPlus></span></button>
          </div>

        </div>
          {/* {collapsable form} */}

          
          {/* <h1  className='text-xl md:text-1xl text-center font-bold py-2'>ENTER THE VENDOR DETAILS HERE</h1> */}

          
            {visible?<Form></Form> :<></>} 
          





        {/* table */}
      <div className='container mx-auto'>
      <h1  className='text-xl md:text-1xl text-center font-bold py-2'>VENDOR INFORMATION TABLE</h1>

      <Table></Table>

      </div>
     
      </main> 
    </section>
  )
}
